name: dotnet package
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 5.0
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
          source-url: https://nuget.pkg.github.com/itn3000/index.json
      - name: build and test binary
        run: pwsh ./build.ps1 --target Test --configuration Release
      - name: collect test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-test-results
          path: DiagnosticSourceLogging.Test/TestResults
      - name: build and pack nuget package(Preview)
        run: pwsh ./build.ps1 --target Pack --configuration Release --version-suffix preview.${{github.run_id}}
        if: ${{!startsWith(github.ref, 'refs/tags/')}}
      - name: build and pack nuget package(Release)
        run: pwsh ./build.ps1 --target Pack --configuration Release
        if: ${{startsWith(github.ref, 'refs/tags/')}}
      - name: collect artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nuget-package
          path: dist/Release
        if: ${{(github.ref == 'refs/heads/master') || (startsWith(github.ref, 'refs/tags')}}
      - name: upload artifacts to github packages
        run: pwsh ./build.ps1 --target Push --api-key ${{ secrets.GITHUB_TOKEN }} --package-source https://nuget.pkg.github.com/itn3000/index.json --configuration Release
        if: ${{(github.ref == 'refs/heads/master') || (startsWith(github.ref, 'refs/tags')}}
      - name: upload artifacts to nuget.org
        run: pwsh ./build.ps1 --target Push --api-key ${{ secrets.NUGET_API_KEY }} --package-source https://api.nuget.org/v3/index.json --configuration Release
        if: ${{startsWith(github.ref, 'refs/tags')}}
