name: dotnet package
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 5.0
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
          source-url: https://nuget.pkg.github.com/itn3000/index.json
      - name: build and test binary
        run: pwsh ./build.ps1 --target Test --configuration Release
      - name: collect test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-test-results
          path: DiagnosticSourceLogging.Test/TestResults
      - name: build and pack nuget package
        run: pwsh ./build.ps1 --target Pack --configuration Release --version-suffix 
      - name: collect artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nuget-package
          path: dist/Release
